# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typolima < Formula
  desc "Conservative typographic fixer for HTML, PHP and text"
  homepage "https://github.com/heptau/typolima"
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heptau/typolima/releases/download/v1.0.0/typolima-1.0.0-darwin-amd64.tar.gz"
    sha256 "e346fce5c9c2f41070a5fb908a39314c317772f3c5e2baa867f6ecca65833339"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heptau/typolima/releases/download/v1.0.0/typolima-1.0.0-darwin-arm64.tar.gz"
    sha256 "bfc078bd7ac290c398d3fe2b1a7c1386ac315dad1aa844c7ea1eaba00c0a4712"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
end
