# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typolima < Formula
  desc "Conservative typographic fixer for HTML, PHP and text"
  homepage "https://github.com/heptau/typolima"
  version "1.2.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heptau/typolima/releases/download/v1.2.4/typolima-1.2.4-darwin-amd64.tar.gz"
    sha256 "4277d9befaa0b5cd9673cc96a5d2ea824fe8ef0497c5a18580ab80e6811d9a9c"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heptau/typolima/releases/download/v1.2.4/typolima-1.2.4-darwin-arm64.tar.gz"
    sha256 "08c048d388338b48521a4ab9c29a7170e0b961f766b9179fbfebe907ee098804"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
end
