# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typolima < Formula
  desc "Conservative typographic fixer for HTML, PHP and text"
  homepage "https://github.com/heptau/typolima"
  version "1.2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heptau/typolima/releases/download/v1.2.0/typolima-1.2.0-darwin-amd64.tar.gz"
    sha256 "d90ac308c523c6e7b048c574f3b834a5193338966c693d5601528d7c8656e7b3"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heptau/typolima/releases/download/v1.2.0/typolima-1.2.0-darwin-arm64.tar.gz"
    sha256 "0e0cdbe9f66a7de5c53f688806dc0fe5776795daafa3e45268063ade24c3f2a1"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
end
