# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typolima < Formula
  desc "Conservative typographic fixer for HTML, PHP and text"
  homepage "https://github.com/heptau/typolima"
  version "1.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heptau/typolima/releases/download/v1.1.0/typolima-1.1.0-darwin-amd64.tar.gz"
    sha256 "9780fc3d7aa26298054965e67c3ff428b366ddd6e42cf022dcf6e0ca9076fbce"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heptau/typolima/releases/download/v1.1.0/typolima-1.1.0-darwin-arm64.tar.gz"
    sha256 "3ec6e34adae180674b2e03d1c5d82b544c233f2acd6b40e842dcc700c735d97e"

    define_method(:install) do
      # We ignore the go-dummy and install the real python one
      bin.install "release/typolima-#{version}-macos" => "typolima"
    end
  end
end
